#!/bin/bash
# RCON Setup Script
# Enables and configures RCON for the Minecraft server

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Get script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
SERVER_PROPERTIES="${PROJECT_DIR}/server.properties"
RCON_CONFIG="${PROJECT_DIR}/config/rcon.conf"

# Function to generate secure password
generate_password() {
    local length=${1:-16}
    # Generate random password using /dev/urandom
    if [ -c /dev/urandom ]; then
        tr -dc 'A-Za-z0-9!@#$%^&*' < /dev/urandom | head -c "$length"
        echo
    else
        # Fallback for systems without /dev/urandom
        openssl rand -base64 "$length" | tr -d "=+/" | cut -c1-"$length"
    fi
}

# Function to enable RCON
enable_rcon() {
    local password="$1"
    local port="${2:-25575}"

    if [ -z "$password" ]; then
        echo -e "${YELLOW}Generating secure RCON password...${NC}"
        password=$(generate_password 20)
    fi

    if [ ! -f "$SERVER_PROPERTIES" ]; then
        echo -e "${RED}Error: server.properties not found${NC}"
        return 1
    fi

    echo -e "${BLUE}Enabling RCON...${NC}"

    # Backup server.properties
    cp "$SERVER_PROPERTIES" "${SERVER_PROPERTIES}.bak"

    # Enable RCON
    if grep -q "^enable-rcon=" "$SERVER_PROPERTIES"; then
        sed -i.bak "s/^enable-rcon=.*/enable-rcon=true/" "$SERVER_PROPERTIES"
    else
        echo "enable-rcon=true" >> "$SERVER_PROPERTIES"
    fi

    # Set RCON port
    if grep -q "^rcon.port=" "$SERVER_PROPERTIES"; then
        sed -i.bak "s/^rcon.port=.*/rcon.port=$port/" "$SERVER_PROPERTIES"
    else
        echo "rcon.port=$port" >> "$SERVER_PROPERTIES"
    fi

    # Set RCON password
    if grep -q "^rcon.password=" "$SERVER_PROPERTIES"; then
        sed -i.bak "s/^rcon.password=.*/rcon.password=$password/" "$SERVER_PROPERTIES"
    else
        echo "rcon.password=$password" >> "$SERVER_PROPERTIES"
    fi

    rm -f "${SERVER_PROPERTIES}.bak"

    # Save RCON config for client
    mkdir -p "$(dirname "$RCON_CONFIG")"
    cat > "$RCON_CONFIG" <<EOF
# RCON Configuration
# Auto-generated by rcon-setup.sh
RCON_HOST=localhost
RCON_PORT=$port
RCON_PASSWORD=$password
EOF
    chmod 600 "$RCON_CONFIG"

    echo -e "${GREEN}RCON enabled${NC}"
    echo -e "${BLUE}RCON Port: $port${NC}"
    echo -e "${BLUE}RCON Password: $password${NC}"
    echo ""
    echo -e "${YELLOW}IMPORTANT: Save this password securely!${NC}"
    echo -e "${YELLOW}Password saved to: $RCON_CONFIG${NC}"
    echo ""
    echo -e "${YELLOW}Note: Restart server for RCON to take effect${NC}"

    # Check if server is running
    if docker ps | grep -q minecraft-server; then
        echo -e "${YELLOW}Server is running. Restart to enable RCON:${NC}"
        echo -e "  ./scripts/manage.sh restart"
    fi
}

# Function to disable RCON
disable_rcon() {
    if [ ! -f "$SERVER_PROPERTIES" ]; then
        echo -e "${RED}Error: server.properties not found${NC}"
        return 1
    fi

    echo -e "${YELLOW}Disabling RCON...${NC}"

    # Backup server.properties
    cp "$SERVER_PROPERTIES" "${SERVER_PROPERTIES}.bak"

    # Disable RCON
    if grep -q "^enable-rcon=" "$SERVER_PROPERTIES"; then
        sed -i.bak "s/^enable-rcon=.*/enable-rcon=false/" "$SERVER_PROPERTIES"
    fi

    # Clear password
    if grep -q "^rcon.password=" "$SERVER_PROPERTIES"; then
        sed -i.bak "s/^rcon.password=.*/rcon.password=/" "$SERVER_PROPERTIES"
    fi

    rm -f "${SERVER_PROPERTIES}.bak"

    echo -e "${GREEN}RCON disabled${NC}"
    echo -e "${YELLOW}Note: Restart server for changes to take effect${NC}"
}

# Function to change RCON password
change_password() {
    local new_password="$1"

    if [ -z "$new_password" ]; then
        echo -e "${YELLOW}Generating new secure password...${NC}"
        new_password=$(generate_password 20)
    fi

    if [ ! -f "$SERVER_PROPERTIES" ]; then
        echo -e "${RED}Error: server.properties not found${NC}"
        return 1
    fi

    # Check if RCON is enabled
    if ! grep -q "^enable-rcon=true" "$SERVER_PROPERTIES"; then
        echo -e "${RED}Error: RCON is not enabled${NC}"
        echo -e "${YELLOW}Run: $0 enable${NC}"
        return 1
    fi

    echo -e "${BLUE}Changing RCON password...${NC}"

    # Backup server.properties
    cp "$SERVER_PROPERTIES" "${SERVER_PROPERTIES}.bak"

    # Update password
    if grep -q "^rcon.password=" "$SERVER_PROPERTIES"; then
        sed -i.bak "s/^rcon.password=.*/rcon.password=$new_password/" "$SERVER_PROPERTIES"
    else
        echo "rcon.password=$new_password" >> "$SERVER_PROPERTIES"
    fi

    rm -f "${SERVER_PROPERTIES}.bak"

    # Update RCON config
    if [ -f "$RCON_CONFIG" ]; then
        local port=$(grep "^RCON_PORT=" "$RCON_CONFIG" | cut -d'=' -f2 || echo "25575")
        cat > "$RCON_CONFIG" <<EOF
# RCON Configuration
RCON_HOST=localhost
RCON_PORT=$port
RCON_PASSWORD=$new_password
EOF
        chmod 600 "$RCON_CONFIG"
    fi

    echo -e "${GREEN}RCON password changed${NC}"
    echo -e "${BLUE}New Password: $new_password${NC}"
    echo ""
    echo -e "${YELLOW}IMPORTANT: Save this password securely!${NC}"
    echo -e "${YELLOW}Note: Restart server for new password to take effect${NC}"
}

# Function to show RCON status
show_status() {
    echo -e "${BLUE}RCON Status${NC}"
    echo "==========="

    if [ ! -f "$SERVER_PROPERTIES" ]; then
        echo -e "${RED}Error: server.properties not found${NC}"
        return 1
    fi

    local enabled=$(grep "^enable-rcon=" "$SERVER_PROPERTIES" | cut -d'=' -f2 || echo "false")
    local port=$(grep "^rcon.port=" "$SERVER_PROPERTIES" | cut -d'=' -f2 || echo "25575")
    local has_password=$(grep "^rcon.password=" "$SERVER_PROPERTIES" | cut -d'=' -f2 || echo "")

    echo "Enabled: $enabled"
    echo "Port: $port"

    if [ "$enabled" = "true" ] && [ -n "$has_password" ]; then
        echo -e "Password: ${GREEN}Set${NC}"
    else
        echo -e "Password: ${RED}Not set${NC}"
    fi

    # Check if RCON config exists
    if [ -f "$RCON_CONFIG" ]; then
        echo ""
        echo -e "${GREEN}RCON client configuration found${NC}"
    else
        echo ""
        echo -e "${YELLOW}RCON client configuration not found${NC}"
        echo -e "${YELLOW}Run: $0 enable${NC}"
    fi
}

# Function to display usage
usage() {
    echo -e "${BLUE}RCON Setup for Minecraft Server${NC}"
    echo ""
    echo "Usage: $0 {enable|disable|change-password|status} [options]"
    echo ""
    echo "Commands:"
    echo "  enable [password] [port]  - Enable RCON (generates password if not provided)"
    echo "  disable                   - Disable RCON"
    echo "  change-password [pass]    - Change RCON password"
    echo "  status                    - Show RCON status"
    echo ""
    echo "Examples:"
    echo "  $0 enable                    # Enable with auto-generated password"
    echo "  $0 enable mypassword          # Enable with custom password"
    echo "  $0 enable mypassword 25576    # Enable with custom password and port"
    echo "  $0 change-password           # Generate new password"
    echo "  $0 status                    # Show current RCON status"
    echo ""
    exit 1
}

# Main function
main() {
    case "${1:-}" in
        enable)
            enable_rcon "$2" "$3"
            ;;
        disable)
            disable_rcon
            ;;
        change-password)
            change_password "$2"
            ;;
        status)
            show_status
            ;;
        *)
            usage
            ;;
    esac
}

# Run main function
main "$@"

